// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type DataTrip struct {
	ID             int64
	VehiclePrefix  string
	Latitude       float32
	Longitude      float32
	ShapeID        string
	TripID         string
	TripStatus     string
	TripProgress   int16
	TripDelay      int16
	StopDistance   float32
	StopOrder      int16
	ReportTimeDiff int16
}
